PROJECT=smallSet
DEPENDENCIES=
LIBRARIES=sserver
LIB_DIRECTORY=lib
OBJ_DIRECTORY=obj
HEADERS= $(PROJECT:=.h) $(DEPENDENCIES:=.h) $(LIBRARIES:%=$(LIB_DIRECTORY)/%.h)
SRC_EXT=.cpp #Either .cpp or .c, depending on project language
COMPILER=g++
COMPILE_FLAGS=-Wall -std=c++11
$(warning $(HEADERS))
$(PROJECT): $(OBJ_DIRECTORY) $(LIB_DIRECTORY)/$(OBJ_DIRECTORY) $(OBJ_DIRECTORY)/$(PROJECT:=.o) $(DEPENDENCIES:%=$(OBJ_DIRECTORY)/%.o) $(LIBRARIES:%=$(LIB_DIRECTORY)/$(OBJ_DIRECTORY)/%.o)
	$(COMPILER) $(COMPILE_FLAGS) $(DEPENDENCIES:%=$</%.o) $(LIBRARIES:%=$(LIB_DIRECTORY)/$(OBJ_DIRECTORY)/%.o) $(PROJECT:%=$(OBJ_DIRECTORY)/%.o) -o $@
$(OBJ_DIRECTORY):
	mkdir $@
$(LIB_DIRECTORY)/$(OBJ_DIRECTORY):
	mkdir $@
$(OBJ_DIRECTORY)/%.o: %$(SRC_EXT) $(HEADERS)
	$(COMPILER) $(COMPILE_FLAGS) -c $< -o $@
$(LIB_DIRECTORY)/$(OBJ_DIRECTORY)/%.o: $(LIB_DIRECTORY)/%$(SRC_EXT) $(HEADERS)
	$(COMPILER) $(COMPILE_FLAGS) -c $< -o $@
.PHONY: clean
clean:
	-rm -r $(OBJ_DIRECTORY)
	-rm -r $(LIB_DIRECTORY)/$(OBJ_DIRECTORY)
	-rm $(PROJECT)
